[package]
name = "iso-10303-parts"
version = "0.1.0"
authors = ["Junfeng Liu <china.liujunfeng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iso-10303 = {version = "*",  path = "../"}