[package]
name = "iso-10303"
version = "0.0.0"
authors = ["Junfeng Liu <china.liujunfeng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pom = "3.1.0"